services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      # root 비밀번호
      MYSQL_DATABASE: mydb                   # 생성할 데이터베이스
      MYSQL_USER: myuser                     # 생성할 사용자
      MYSQL_PASSWORD: mypassword             # 사용자 비밀번호
    ports:
      - "3306:3306"
